[build]
publish = "static"
command = "pyenv install 3.9 && pip install -r requirements.txt && gunicorn app:app"

[[redirects]]
# Redirect all routes to your Flask server
from = "/*"
to = "/"
status = 200
